In [1]:
import pandas as pd

# Specify the file names
file_names = ['part1_with_obj.csv', 'part2_with_obj.csv', 'part3_with_obj.csv', 'part4_with_obj.csv', 'part5_with_obj.csv']

# Create an empty list to store the dataframes
dfs = []

# Iterate through each file
for file_name in file_names:
    # Read the CSV file and append to the list
    df = pd.read_csv(file_name)
    dfs.append(df)

# Concatenate the dataframes into one
merged_df = pd.concat(dfs, ignore_index=True)

# Write the merged dataframe to a CSV file
merged_df.to_csv('merged_dataset.csv', index=False)

In [2]:
import pandas as pd
df = pd.read_csv('movie_object_frequency.csv')
df

,youtubeId,movieId,title,trailer_present,video downloaded,Durations,FPS,Width,Height,Aspect Ratio,...,70,71,72,73,74,75,76,77,78,79
0,K26_sDKnvMU,1,Toy Story (1995),1,0,90,29,636,480,1.32,...,0,0,1,33,0,1,0,5,0,1
1,3LPANjHlPxo,2,Jumanji (1995),1,0,167,23,1280,720,1.78,...,0,0,0,9,16,14,4,0,0,3
2,rEnOoWs3FuA,3,Grumpier Old Men (1995),1,0,111,29,640,360,1.78,...,0,0,0,0,0,2,0,0,0,0
3,j9xml1CxgXI,4,Waiting to Exhale (1995),1,0,159,23,640,480,1.33,...,0,0,0,0,2,0,0,0,0,0
4,2GfZl4kuVNI,6,Heat (1995),1,0,147,24,1920,1080,1.78,...,0,0,2,0,0,0,1,0,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6442,_Buvv8StMGw,130682,Muck (2015),1,0,86,23,1280,720,1.78,...,0,4,0,0,0,1,2,0,0,0
6443,qCD9BG7ioOc,130970,George Carlin: Life Is Worth Losing (2005),1,0,267,29,1920,1080,1.78,...,0,0,0,0,0,0,0,0,0,402
6444,zElDJ1f3Jk0,130980,The Day That Lasted 21 Years (2012),1,0,116,29,1920,1080,1.78,...,0,0,0,1,5,27,0,0,0,0
6445,lEqrpuU9fYI,131013,Get Hard (2015),1,0,144,23,1280,720,1.78,...,0,0,28,5,0,19,0,0,0,0
6446,zildFIFKjlc,131168,Phoenix (2014),1,0,124,23,1920,816,2.35,...,0,0,2,14,6,0,0,0,0,0

In [3]:
df = df[df['0'] != 0]
df

,youtubeId,movieId,title,trailer_present,video downloaded,Durations,FPS,Width,Height,Aspect Ratio,...,70,71,72,73,74,75,76,77,78,79
0,K26_sDKnvMU,1,Toy Story (1995),1,0,90,29,636,480,1.32,...,0,0,1,33,0,1,0,5,0,1
1,3LPANjHlPxo,2,Jumanji (1995),1,0,167,23,1280,720,1.78,...,0,0,0,9,16,14,4,0,0,3
2,rEnOoWs3FuA,3,Grumpier Old Men (1995),1,0,111,29,640,360,1.78,...,0,0,0,0,0,2,0,0,0,0
3,j9xml1CxgXI,4,Waiting to Exhale (1995),1,0,159,23,640,480,1.33,...,0,0,0,0,2,0,0,0,0,0
4,2GfZl4kuVNI,6,Heat (1995),1,0,147,24,1920,1080,1.78,...,0,0,2,0,0,0,1,0,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6442,_Buvv8StMGw,130682,Muck (2015),1,0,86,23,1280,720,1.78,...,0,4,0,0,0,1,2,0,0,0
6443,qCD9BG7ioOc,130970,George Carlin: Life Is Worth Losing (2005),1,0,267,29,1920,1080,1.78,...,0,0,0,0,0,0,0,0,0,402
6444,zElDJ1f3Jk0,130980,The Day That Lasted 21 Years (2012),1,0,116,29,1920,1080,1.78,...,0,0,0,1,5,27,0,0,0,0
6445,lEqrpuU9fYI,131013,Get Hard (2015),1,0,144,23,1280,720,1.78,...,0,0,28,5,0,19,0,0,0,0
6446,zildFIFKjlc,131168,Phoenix (2014),1,0,124,23,1920,816,2.35,...,0,0,2,14,6,0,0,0,0,0

In [4]:
df = df[df['Durations'] < 600]
df

,youtubeId,movieId,title,trailer_present,video downloaded,Durations,FPS,Width,Height,Aspect Ratio,...,70,71,72,73,74,75,76,77,78,79
0,K26_sDKnvMU,1,Toy Story (1995),1,0,90,29,636,480,1.32,...,0,0,1,33,0,1,0,5,0,1
1,3LPANjHlPxo,2,Jumanji (1995),1,0,167,23,1280,720,1.78,...,0,0,0,9,16,14,4,0,0,3
2,rEnOoWs3FuA,3,Grumpier Old Men (1995),1,0,111,29,640,360,1.78,...,0,0,0,0,0,2,0,0,0,0
3,j9xml1CxgXI,4,Waiting to Exhale (1995),1,0,159,23,640,480,1.33,...,0,0,0,0,2,0,0,0,0,0
4,2GfZl4kuVNI,6,Heat (1995),1,0,147,24,1920,1080,1.78,...,0,0,2,0,0,0,1,0,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6442,_Buvv8StMGw,130682,Muck (2015),1,0,86,23,1280,720,1.78,...,0,4,0,0,0,1,2,0,0,0
6443,qCD9BG7ioOc,130970,George Carlin: Life Is Worth Losing (2005),1,0,267,29,1920,1080,1.78,...,0,0,0,0,0,0,0,0,0,402
6444,zElDJ1f3Jk0,130980,The Day That Lasted 21 Years (2012),1,0,116,29,1920,1080,1.78,...,0,0,0,1,5,27,0,0,0,0
6445,lEqrpuU9fYI,131013,Get Hard (2015),1,0,144,23,1280,720,1.78,...,0,0,28,5,0,19,0,0,0,0
6446,zildFIFKjlc,131168,Phoenix (2014),1,0,124,23,1920,816,2.35,...,0,0,2,14,6,0,0,0,0,0

In [5]:
df = df.reset_index(drop=True)
df

,youtubeId,movieId,title,trailer_present,video downloaded,Durations,FPS,Width,Height,Aspect Ratio,...,70,71,72,73,74,75,76,77,78,79
0,K26_sDKnvMU,1,Toy Story (1995),1,0,90,29,636,480,1.32,...,0,0,1,33,0,1,0,5,0,1
1,3LPANjHlPxo,2,Jumanji (1995),1,0,167,23,1280,720,1.78,...,0,0,0,9,16,14,4,0,0,3
2,rEnOoWs3FuA,3,Grumpier Old Men (1995),1,0,111,29,640,360,1.78,...,0,0,0,0,0,2,0,0,0,0
3,j9xml1CxgXI,4,Waiting to Exhale (1995),1,0,159,23,640,480,1.33,...,0,0,0,0,2,0,0,0,0,0
4,2GfZl4kuVNI,6,Heat (1995),1,0,147,24,1920,1080,1.78,...,0,0,2,0,0,0,1,0,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6342,_Buvv8StMGw,130682,Muck (2015),1,0,86,23,1280,720,1.78,...,0,4,0,0,0,1,2,0,0,0
6343,qCD9BG7ioOc,130970,George Carlin: Life Is Worth Losing (2005),1,0,267,29,1920,1080,1.78,...,0,0,0,0,0,0,0,0,0,402
6344,zElDJ1f3Jk0,130980,The Day That Lasted 21 Years (2012),1,0,116,29,1920,1080,1.78,...,0,0,0,1,5,27,0,0,0,0
6345,lEqrpuU9fYI,131013,Get Hard (2015),1,0,144,23,1280,720,1.78,...,0,0,28,5,0,19,0,0,0,0
6346,zildFIFKjlc,131168,Phoenix (2014),1,0,124,23,1920,816,2.35,...,0,0,2,14,6,0,0,0,0,0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6347 entries, 0 to 6346
Data columns (total 90 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   youtubeId         6347 non-null   object
 1   movieId           6347 non-null   int64
 2   title             6347 non-null   object
 3   trailer_present   6347 non-null   int64
 4   video downloaded  6347 non-null   int64
 5   Durations         6347 non-null   int64
 6   FPS               6347 non-null   int64
 7   Width             6347 non-null   int64
 8   Height            6347 non-null   int64
 9   Aspect Ratio      6347 non-null   float64
 10  0                 6347 non-null   int64
 11  1                 6347 non-null   int64
 12  2                 6347 non-null   int64
 13  3                 6347 non-null   int64
 14  4                 6347 non-null   int64
 15  5                 6347 non-null   int64
 16  6                 6347 non-null   int64
 17  7                 6347 non-null   int64
 18  8                 6347 non-null   int64
 19  9                 6347 non-null   int64
 20  10                6347 non-null   int64
 21  11                6347 non-null   int64
 22  12                6347 non-null   int64
 23  13                6347 non-null   int64
 24  14                6347 non-null   int64
 25  15                6347 non-null   int64
 26  16                6347 non-null   int64
 27  17                6347 non-null   int64
 28  18                6347 non-null   int64
 29  19                6347 non-null   int64
 30  20                6347 non-null   int64
 31  21                6347 non-null   int64
 32  22                6347 non-null   int64
 33  23                6347 non-null   int64
 34  24                6347 non-null   int64
 35  25                6347 non-null   int64
 36  26                6347 non-null   int64
 37  27                6347 non-null   int64
 38  28                6347 non-null   int64
 39  29                6347 non-null   int64
 40  30                6347 non-null   int64
 41  31                6347 non-null   int64
 42  32                6347 non-null   int64
 43  33                6347 non-null   int64
 44  34                6347 non-null   int64
 45  35                6347 non-null   int64
 46  36                6347 non-null   int64
 47  37                6347 non-null   int64
 48  38                6347 non-null   int64
 49  39                6347 non-null   int64
 50  40                6347 non-null   int64
 51  41                6347 non-null   int64
 52  42                6347 non-null   int64
 53  43                6347 non-null   int64
 54  44                6347 non-null   int64
 55  45                6347 non-null   int64
 56  46                6347 non-null   int64
 57  47                6347 non-null   int64
 58  48                6347 non-null   int64
 59  49                6347 non-null   int64
 60  50                6347 non-null   int64
 61  51                6347 non-null   int64
 62  52                6347 non-null   int64
 63  53                6347 non-null   int64
 64  54                6347 non-null   int64
 65  55                6347 non-null   int64
 66  56                6347 non-null   int64
 67  57                6347 non-null   int64
 68  58                6347 non-null   int64
 69  59                6347 non-null   int64
 70  60                6347 non-null   int64
 71  61                6347 non-null   int64
 72  62                6347 non-null   int64
 73  63                6347 non-null   int64
 74  64                6347 non-null   int64
 75  65                6347 non-null   int64
 76  66                6347 non-null   int64
 77  67                6347 non-null   int64
 78  68                6347 non-null   int64
 79  69                6347 non-null   int64
 80  70                6347 non-null   int64
 81  71                6347 non-null   int64
 82  72                6347 non-null   int64
 83  73                6347 non-null   int64
 84  74                6347 non-null   int64
 85  75                6347 non-null   int64
 86  76                6347 non-null   int64
 87  77                6347 non-null   int64
 88  78                6347 non-null   int64
 89  79                6347 non-null   int64
dtypes: float64(1), int64(87), object(2)
memory usage: 4.4+ MB

In [8]:
df

,youtubeId,movieId,title,trailer_present,video downloaded,Durations,FPS,Width,Height,Aspect Ratio,...,70,71,72,73,74,75,76,77,78,79
0,K26_sDKnvMU,1,Toy Story (1995),1,0,90,29,636,480,1.32,...,0,0,1,33,0,1,0,5,0,1
1,3LPANjHlPxo,2,Jumanji (1995),1,0,167,23,1280,720,1.78,...,0,0,0,9,16,14,4,0,0,3
2,rEnOoWs3FuA,3,Grumpier Old Men (1995),1,0,111,29,640,360,1.78,...,0,0,0,0,0,2,0,0,0,0
3,j9xml1CxgXI,4,Waiting to Exhale (1995),1,0,159,23,640,480,1.33,...,0,0,0,0,2,0,0,0,0,0
4,2GfZl4kuVNI,6,Heat (1995),1,0,147,24,1920,1080,1.78,...,0,0,2,0,0,0,1,0,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6342,_Buvv8StMGw,130682,Muck (2015),1,0,86,23,1280,720,1.78,...,0,4,0,0,0,1,2,0,0,0
6343,qCD9BG7ioOc,130970,George Carlin: Life Is Worth Losing (2005),1,0,267,29,1920,1080,1.78,...,0,0,0,0,0,0,0,0,0,402
6344,zElDJ1f3Jk0,130980,The Day That Lasted 21 Years (2012),1,0,116,29,1920,1080,1.78,...,0,0,0,1,5,27,0,0,0,0
6345,lEqrpuU9fYI,131013,Get Hard (2015),1,0,144,23,1280,720,1.78,...,0,0,28,5,0,19,0,0,0,0
6346,zildFIFKjlc,131168,Phoenix (2014),1,0,124,23,1920,816,2.35,...,0,0,2,14,6,0,0,0,0,0

In [9]:
df.to_csv('All_parts_objects.csv')

In [7]:
# Select the feature columns '0' through '79'
feature_columns = [str(i) for i in range(80)]
feature_df = df[feature_columns]
feature_df

,0,1,2,3,4,5,6,7,8,9,...,70,71,72,73,74,75,76,77,78,79
0,194,0,1,1,3,0,0,1,0,0,...,0,0,1,33,0,1,0,5,0,1
1,629,0,43,0,3,0,0,5,0,2,...,0,0,0,9,16,14,4,0,0,3
2,709,0,11,0,0,0,0,2,26,0,...,0,0,0,0,0,2,0,0,0,0
3,1141,0,22,0,0,0,0,8,0,1,...,0,0,0,0,2,0,0,0,0,0
4,1049,0,115,0,12,5,1,11,0,9,...,0,0,2,0,0,0,1,0,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6342,282,0,0,0,0,0,0,0,0,0,...,0,4,0,0,0,1,2,0,0,0
6343,1731,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,402
6344,170,0,2,5,210,0,0,1,101,0,...,0,0,0,1,5,27,0,0,0,0
6345,1484,0,149,2,1,1,0,18,5,0,...,0,0,28,5,0,19,0,0,0,0
6346,713,0,12,1,0,0,0,9,0,0,...,0,0,2,14,6,0,0,0,0,0

In [32]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

# Because PCA requires dense data, we need to scale the features first
scaler = StandardScaler(with_mean=False)  # with_mean=False is important for sparse matrices
feature_df_scaled = scaler.fit_transform(feature_df)

# Apply PCA to reduce the feature space to a smaller number of dimensions
pca = PCA(n_components=0.3)  # Keep 95% of variance
feature_df_reduced = pca.fit_transform(feature_df_scaled)

# Compute the cosine similarity matrix on the reduced features
similarity_matrix_reduced = cosine_similarity(feature_df_reduced)

# Create a DataFrame for the reduced similarity matrix with movieId as index and columns
similarity_df_reduced = pd.DataFrame(similarity_matrix_reduced, index=df['movieId'], columns=df['movieId'])

In [33]:
feature_df_reduced.shape

(6347, 14)

In [34]:
similarity_df_reduced

movieId,1,2,3,4,6,7,8,10,11,12,...,130087,130351,130580,130628,130642,130682,130970,130980,131013,131168
movieId,,,,,,,,,,,,,,,,,,,,,
1,1.000000,-0.243104,0.504629,-0.344104,-0.143003,-0.464393,0.579768,0.237780,-0.501352,0.293614,...,-0.370044,-0.365191,-0.419201,0.019810,0.207069,0.566476,0.256597,0.377690,-0.552737,-0.229393
2,-0.243104,1.000000,-0.124966,0.112549,-0.149269,-0.183313,-0.123560,0.038243,-0.086291,-0.107879,...,0.022655,-0.050985,-0.007112,0.008570,0.017874,-0.055071,0.062113,0.096882,0.021592,-0.294686
3,0.504629,-0.124966,1.000000,-0.335106,-0.250953,-0.345815,0.483088,-0.088566,-0.346131,0.292455,...,-0.560547,-0.248211,-0.272644,0.147504,0.078213,0.325331,-0.376014,0.266896,-0.609727,-0.127379
4,-0.344104,0.112549,-0.335106,1.000000,-0.021616,0.324454,-0.339278,-0.186645,0.572099,-0.216366,...,0.490443,-0.000666,0.091495,0.050672,-0.231126,-0.339565,0.185840,-0.423195,0.502669,0.387433
6,-0.143003,-0.149269,-0.250953,-0.021616,1.000000,0.166424,-0.120874,0.506491,-0.010228,-0.134074,...,0.505210,0.273424,-0.086426,-0.155465,-0.177107,-0.225311,0.056380,-0.080488,-0.102623,-0.103312
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130682,0.566476,-0.055071,0.325331,-0.339565,-0.225311,-0.662604,0.891513,-0.222538,-0.562423,0.463149,...,-0.555834,-0.327063,-0.352055,-0.078585,0.511608,1.000000,-0.072768,-0.122274,-0.425179,0.215104
130970,0.256597,0.062113,-0.376014,0.185840,0.056380,0.002677,-0.133694,0.251636,-0.113127,-0.168097,...,0.400360,-0.101790,-0.150783,-0.027761,0.321827,-0.072768,1.000000,-0.014655,0.044579,-0.296932
130980,0.377690,0.096882,0.266896,-0.423195,-0.080488,-0.414865,0.014685,0.497802,-0.208966,0.243823,...,-0.364654,-0.324785,-0.197033,0.183525,-0.191128,-0.122274,-0.014655,1.000000,-0.343993,-0.457028
131013,-0.552737,0.021592,-0.609727,0.502669,-0.102623,0.306385,-0.719509,-0.187525,0.432977,-0.338452,...,0.545327,0.238482,0.365926,-0.090424,-0.514478,-0.425179,0.044579,-0.343993,1.000000,0.142000
131168,-0.229393,-0.294686,-0.127379,0.387433,-0.103312,0.136367,0.237240,-0.606671,0.518160,0.378600,...,-0.207652,-0.219668,-0.172886,-0.148290,0.054393,0.215104,-0.296932,-0.457028,0.142000,1.000000

In [35]:
similarity_df_reduced.to_csv('movie_similarity_based_on_objects.csv')