In [1]:
import pandas as pd

In [2]:
ratings = pd.read_csv(r'ratings_small_filtered_2.csv', index_col=0)

In [3]:
ratings

       userId  movieId  rating   timestamp
0           1       31     2.5  1260759144
1           1     1061     3.0  1260759182
2           1     1129     2.0  1260759185
3           1     1172     4.0  1260759205
4           1     1263     2.0  1260759151
...       ...      ...     ...         ...
81725     671     6212     2.5  1065149436
81726     671     6268     2.5  1065579370
81727     671     6365     4.0  1070940363
81728     671     6385     2.5  1070979663
81729     671     6565     3.5  1074784724

[81730 rows x 4 columns]

In [4]:
ratings.info()

<class 'pandas.core.frame.DataFrame'>
Index: 81730 entries, 0 to 81729
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   userId     81730 non-null  int64
 1   movieId    81730 non-null  int64
 2   rating     81730 non-null  float64
 3   timestamp  81730 non-null  int64
dtypes: float64(1), int64(3)
memory usage: 3.1 MB

In [5]:
ratings['rating'] = ratings['rating'].apply(lambda x: 1 if x > 3.5 else 0)

In [6]:
ratings

       userId  movieId  rating   timestamp
0           1       31       0  1260759144
1           1     1061       0  1260759182
2           1     1129       0  1260759185
3           1     1172       1  1260759205
4           1     1263       0  1260759151
...       ...      ...     ...         ...
81725     671     6212       0  1065149436
81726     671     6268       0  1065579370
81727     671     6365       1  1070940363
81728     671     6385       0  1070979663
81729     671     6565       0  1074784724

[81730 rows x 4 columns]

In [7]:
ratings.info()

<class 'pandas.core.frame.DataFrame'>
Index: 81730 entries, 0 to 81729
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   userId     81730 non-null  int64
 1   movieId    81730 non-null  int64
 2   rating     81730 non-null  int64
 3   timestamp  81730 non-null  int64
dtypes: int64(4)
memory usage: 3.1 MB

In [8]:
import pandas as pd
from sklearn.preprocessing import normalize

In [9]:
# Assuming 'ratings' is your DataFrame
user_movie_matrix = ratings.pivot_table(index='userId', columns='movieId', values='rating')
user_movie_matrix

movieId,1,2,3,4,6,7,8,10,11,12,...,130087,130351,130580,130628,130642,130682,130970,130980,131013,131168
userId,,,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
667,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
668,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
669,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
670,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
671,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
# Replace missing values (NaN) with 0.5
user_movie_matrix = user_movie_matrix.fillna(-1)
user_movie_matrix

movieId,1,2,3,4,6,7,8,10,11,12,...,130087,130351,130580,130628,130642,130682,130970,130980,131013,131168
userId,,,,,,,,,,,,,,,,,,,,,
1,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
2,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,1.0,-1.0,-1.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
3,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
4,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,1.0,-1.0,-1.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
5,-1.0,-1.0,1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
667,-1.0,-1.0,-1.0,-1.0,1.0,-1.0,-1.0,-1.0,0.0,-1.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
668,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
669,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
670,1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
671,1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0

In [11]:
# Normalize the matrix using L2-norm
user_movie_matrix_normalized = normalize(user_movie_matrix, norm='l2', axis=0)
user_movie_matrix_normalized

array([[-0.04141577, -0.04065578, -0.03971507, ..., -0.03860457,
        -0.03872015, -0.03860457],
       [-0.04141577, -0.04065578, -0.03971507, ..., -0.03860457,
        -0.03872015, -0.03860457],
       [-0.04141577, -0.04065578, -0.03971507, ..., -0.03860457,
        -0.03872015, -0.03860457],
       ...,
       [-0.04141577, -0.04065578, -0.03971507, ..., -0.03860457,
        -0.03872015, -0.03860457],
       [ 0.04141577, -0.04065578, -0.03971507, ..., -0.03860457,
        -0.03872015, -0.03860457],
       [ 0.04141577, -0.04065578, -0.03971507, ..., -0.03860457,
        -0.03872015, -0.03860457]])

In [12]:
# Convert the normalized matrix back to a DataFrame
user_movie_matrix_normalized_df = pd.DataFrame(user_movie_matrix_normalized, 
                                               index=user_movie_matrix.index, 
                                               columns=user_movie_matrix.columns)
user_movie_matrix_normalized_df

movieId,1,2,3,4,6,7,8,10,11,12,...,130087,130351,130580,130628,130642,130682,130970,130980,131013,131168
userId,,,,,,,,,,,,,,,,,,,,,
1,-0.041416,-0.040656,-0.039715,-0.038984,-0.039715,-0.03959,-0.038633,-0.040927,-0.039715,-0.039014,...,-0.038633,-0.038605,-0.038633,-0.038605,-0.038633,-0.038633,-0.038605,-0.038605,-0.03872,-0.038605
2,-0.041416,-0.040656,-0.039715,-0.038984,-0.039715,-0.03959,-0.038633,0.040927,-0.039715,-0.039014,...,-0.038633,-0.038605,-0.038633,-0.038605,-0.038633,-0.038633,-0.038605,-0.038605,-0.03872,-0.038605
3,-0.041416,-0.040656,-0.039715,-0.038984,-0.039715,-0.03959,-0.038633,-0.040927,-0.039715,-0.039014,...,-0.038633,-0.038605,-0.038633,-0.038605,-0.038633,-0.038633,-0.038605,-0.038605,-0.03872,-0.038605
4,-0.041416,-0.040656,-0.039715,-0.038984,-0.039715,-0.03959,-0.038633,0.040927,-0.039715,-0.039014,...,-0.038633,-0.038605,-0.038633,-0.038605,-0.038633,-0.038633,-0.038605,-0.038605,-0.03872,-0.038605
5,-0.041416,-0.040656,0.039715,-0.038984,-0.039715,-0.03959,-0.038633,-0.040927,-0.039715,-0.039014,...,-0.038633,-0.038605,-0.038633,-0.038605,-0.038633,-0.038633,-0.038605,-0.038605,-0.03872,-0.038605
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
667,-0.041416,-0.040656,-0.039715,-0.038984,0.039715,-0.03959,-0.038633,-0.040927,0.000000,-0.039014,...,-0.038633,-0.038605,-0.038633,-0.038605,-0.038633,-0.038633,-0.038605,-0.038605,-0.03872,-0.038605
668,-0.041416,-0.040656,-0.039715,-0.038984,-0.039715,-0.03959,-0.038633,-0.040927,-0.039715,-0.039014,...,-0.038633,-0.038605,-0.038633,-0.038605,-0.038633,-0.038633,-0.038605,-0.038605,-0.03872,-0.038605
669,-0.041416,-0.040656,-0.039715,-0.038984,-0.039715,-0.03959,-0.038633,-0.040927,-0.039715,-0.039014,...,-0.038633,-0.038605,-0.038633,-0.038605,-0.038633,-0.038633,-0.038605,-0.038605,-0.03872,-0.038605
670,0.041416,-0.040656,-0.039715,-0.038984,-0.039715,-0.03959,-0.038633,-0.040927,-0.039715,-0.039014,...,-0.038633,-0.038605,-0.038633,-0.038605,-0.038633,-0.038633,-0.038605,-0.038605,-0.03872,-0.038605
671,0.041416,-0.040656,-0.039715,-0.038984,-0.039715,-0.03959,-0.038633,-0.040927,-0.039715,-0.039014,...,-0.038633,-0.038605,-0.038633,-0.038605,-0.038633,-0.038633,-0.038605,-0.038605,-0.03872,-0.038605

In [13]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics.pairwise import cosine_similarity
from tqdm import tqdm

# Assuming 'user_movie_matrix_normalized_df' is the normalized user-movie ratings matrix
# and 'ratings' is the original ratings DataFrame

In [14]:
# Get the user IDs from the normalized user-movie matrix
user_ids = user_movie_matrix_normalized_df.index

# Filter the ratings DataFrame based on the user IDs
filtered_ratings = ratings[ratings['userId'].isin(user_ids)]

# Create a mapping of user IDs to their indices in the normalized matrix
user_id_to_index = {user_id: index for index, user_id in enumerate(user_ids)}

# Filter the normalized matrix based on the user IDs
filtered_matrix = user_movie_matrix_normalized_df.loc[filtered_ratings['userId']]

# Split the data into features (X) and target variable (y)
X = filtered_matrix.values
y = filtered_ratings['rating'].values  # Assumes 'rating' column contains the target variable (0 or 1)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [15]:
X_train.shape

(65384, 6347)

In [16]:
filtered_matrix

movieId,1,2,3,4,6,7,8,10,11,12,...,130087,130351,130580,130628,130642,130682,130970,130980,131013,131168
userId,,,,,,,,,,,,,,,,,,,,,
1,-0.041416,-0.040656,-0.039715,-0.038984,-0.039715,-0.03959,-0.038633,-0.040927,-0.039715,-0.039014,...,-0.038633,-0.038605,-0.038633,-0.038605,-0.038633,-0.038633,-0.038605,-0.038605,-0.03872,-0.038605
1,-0.041416,-0.040656,-0.039715,-0.038984,-0.039715,-0.03959,-0.038633,-0.040927,-0.039715,-0.039014,...,-0.038633,-0.038605,-0.038633,-0.038605,-0.038633,-0.038633,-0.038605,-0.038605,-0.03872,-0.038605
1,-0.041416,-0.040656,-0.039715,-0.038984,-0.039715,-0.03959,-0.038633,-0.040927,-0.039715,-0.039014,...,-0.038633,-0.038605,-0.038633,-0.038605,-0.038633,-0.038633,-0.038605,-0.038605,-0.03872,-0.038605
1,-0.041416,-0.040656,-0.039715,-0.038984,-0.039715,-0.03959,-0.038633,-0.040927,-0.039715,-0.039014,...,-0.038633,-0.038605,-0.038633,-0.038605,-0.038633,-0.038633,-0.038605,-0.038605,-0.03872,-0.038605
1,-0.041416,-0.040656,-0.039715,-0.038984,-0.039715,-0.03959,-0.038633,-0.040927,-0.039715,-0.039014,...,-0.038633,-0.038605,-0.038633,-0.038605,-0.038633,-0.038633,-0.038605,-0.038605,-0.03872,-0.038605
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
671,0.041416,-0.040656,-0.039715,-0.038984,-0.039715,-0.03959,-0.038633,-0.040927,-0.039715,-0.039014,...,-0.038633,-0.038605,-0.038633,-0.038605,-0.038633,-0.038633,-0.038605,-0.038605,-0.03872,-0.038605
671,0.041416,-0.040656,-0.039715,-0.038984,-0.039715,-0.03959,-0.038633,-0.040927,-0.039715,-0.039014,...,-0.038633,-0.038605,-0.038633,-0.038605,-0.038633,-0.038633,-0.038605,-0.038605,-0.03872,-0.038605
671,0.041416,-0.040656,-0.039715,-0.038984,-0.039715,-0.03959,-0.038633,-0.040927,-0.039715,-0.039014,...,-0.038633,-0.038605,-0.038633,-0.038605,-0.038633,-0.038633,-0.038605,-0.038605,-0.03872,-0.038605
671,0.041416,-0.040656,-0.039715,-0.038984,-0.039715,-0.03959,-0.038633,-0.040927,-0.039715,-0.039014,...,-0.038633,-0.038605,-0.038633,-0.038605,-0.038633,-0.038633,-0.038605,-0.038605,-0.03872,-0.038605
671,0.041416,-0.040656,-0.039715,-0.038984,-0.039715,-0.03959,-0.038633,-0.040927,-0.039715,-0.039014,...,-0.038633,-0.038605,-0.038633,-0.038605,-0.038633,-0.038633,-0.038605,-0.038605,-0.03872,-0.038605

In [17]:
# Create a KNN classifier with cosine similarity
knn = KNeighborsClassifier(n_neighbors=255, metric='cosine')

In [18]:
# Fit the model on the training data
knn.fit(X_train, y_train)

KNeighborsClassifier(metric='cosine', n_neighbors=255)

In [19]:
# Predict the labels for the test set
y_pred = knn.predict(X_test)

In [20]:
# Generate the classification report
print("Classification Report:")
print(classification_report(y_test, y_pred))

# Generate the confusion matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Classification Report:
              precision    recall  f1-score   support

           0       0.57      0.75      0.65      7794
           1       0.68      0.48      0.56      8552

    accuracy                           0.61     16346
   macro avg       0.62      0.62      0.60     16346
weighted avg       0.63      0.61      0.60     16346

Confusion Matrix:
[[5843 1951]
 [4440 4112]]

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix
import numpy as np
from scipy.spatial.distance import mahalanobis

# List of distance metrics
distance_metrics = ['euclidean', 'manhattan', 'chebyshev', 'hamming', 'cosine', 'jaccard']

# Assuming X_train, y_train, X_test, and y_test are already defined
for metric in distance_metrics:
    print(f"Using {metric} distance metric")

    if metric == 'mahalanobis':
        # Calculate the inverse of the covariance matrix for Mahalanobis distance
        cov_matrix = np.cov(X_train, rowvar=False)
        inv_cov_matrix = np.linalg.inv(cov_matrix)
        knn = KNeighborsClassifier(n_neighbors=255, metric=metric, metric_params={'VI': inv_cov_matrix})
    else:
        knn = KNeighborsClassifier(n_neighbors=255, metric=metric)

    # Fit the model on the training data
    knn.fit(X_train, y_train)

    # Predict the labels for the test set
    y_pred = knn.predict(X_test)

    # Generate the classification report
    print("Classification Report:")
    print(classification_report(y_test, y_pred))

    # Generate the confusion matrix
    print("Confusion Matrix:")
    print(confusion_matrix(y_test, y_pred))
    print("\n" + "="*60 + "\n")

Using euclidean distance metric
Classification Report:
              precision    recall  f1-score   support

           0       0.67      0.50      0.57      7794
           1       0.63      0.77      0.70      8552

    accuracy                           0.64     16346
   macro avg       0.65      0.64      0.63     16346
weighted avg       0.65      0.64      0.64     16346

Confusion Matrix:
[[3918 3876]
 [1930 6622]]

============================================================

Using manhattan distance metric
Classification Report:
              precision    recall  f1-score   support

           0       0.67      0.52      0.59      7794
           1       0.64      0.77      0.70      8552

    accuracy                           0.65     16346
   macro avg       0.65      0.64      0.64     16346
weighted avg       0.65      0.65      0.64     16346

Confusion Matrix:
[[4083 3711]
 [2004 6548]]

============================================================

Using chebyshev distance metric